### ISSUE TITLE
I am getting issue while creating ticket

### ISSUE THREAD

**Issue by Habeeb30** [DuckoDas/DJS-Ticket-System-v14#1]
### **[Unhandled Rejection/Catch](https://nodejs.org/api/process.html#event-unhandledrejection)**
**Reason**
```
ExpectedConstraintError > s.string.lengthGreaterThanOrEqual
  Invalid string length

  Expected: expected.length >= 1

  Received:
  | ''

    at Object.run (/app/node_modules/@sapphire/shapeshift/dist/index.js:1503:79)
    at /app/node_modules/@sapphire/shapeshift/dist/index.js:113:66
    at Array.reduce (<anonymous>)
    at StringValidator.parse (/app/node_modules/@sapphire/shapeshift/dist/index.js:113:29)
    at ButtonBuilder.setLabel (/app/node_modules/@discordjs/builders/dist/index.js:535:44)
    at Object.execute (/app/Commands/Staff/Ticket.js:187:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
**Promise**
```
Promise {
  <rejected> [ExpectedConstraintError: s.string.lengthGreaterThanOrEqual]
  
      at Object.run (/app/node_modules/@sapphire/shapeshift/dist/index.js:1503:79)
      at /app/node_modules/@sapphire/shapeshift/dist/index.js:113:66
      at Array.reduce (<anonymous>)
      at StringValidator.parse (/app/node_modules/@sapphire/shapeshift/dist/index.js:113:29)
      at ButtonBuilder.setLabel (/app/node_modules/@discordjs/builders/dist/index.js:535:44)
      at Object.execute (/app/Commands/Staff/Ticket.js:187:16)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
}
```

**Comment by cartiqo** [comment]
Is it possible that there is somewhere that you removed like a description or something like that
